version: 2
updates:
- package-ecosystem: bundler
  directories:
  - "/apps/clinical_exchange"
  - "/gems/gesso"
  - "/gems/conduit"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/apps/clinical_exchange"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
