// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)
